# Generated by Django 3.2.3 on 2021-05-27 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beershareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Placed'), (2, 'Accepted'), (3, 'Declined'), (4, 'Done')])),
                ('beerCellarEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beershareapp.beercellarentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BeerOder',
        ),
    ]
