# Generated by Django 3.2.3 on 2021-05-29 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beershareapp', '0002_auto_20210527_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beercellarentry',
            name='beerCellar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='beershareapp.beercellar'),
        ),
        migrations.AlterField(
            model_name='beercellarentry',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
