# Generated by Django 3.2.3 on 2021-06-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beershareapp', '0005_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beercellar',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
