# Generated by Django 3.2.3 on 2021-06-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beershareapp', '0006_alter_beercellar_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beercellar',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
