# Generated by Django 3.2.3 on 2021-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beershareapp', '0007_alter_beercellar_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beercellar',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='beercellar',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
