# Generated by Django 3.2.3 on 2021-06-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beershareapp', '0008_auto_20210606_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerorder',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Placed'), (2, 'Accepted'), (3, 'Declined'), (4, 'Done')], default=1),
        ),
    ]
