# Generated by Django 3.2.3 on 2021-06-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beershareapp', '0009_alter_beerorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beerorder',
            options={'ordering': ['datetime']},
        ),
        migrations.RemoveField(
            model_name='beerorder',
            name='beerCellarEntry',
        ),
        migrations.AddField(
            model_name='beerorder',
            name='beer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='beershareapp.beer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beerorder',
            name='beerCellar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beershareapp.beercellar'),
            preserve_default=False,
        ),
    ]
